#!/bin/bash

crawling() {
    # Get the list of live subdomains from the httpx_live_subdomains.txt file generated by the httpx_recon.sh script
    input_file="$REPORT_DIR/httpx_live_subdomains.txt"

    # Check if the input file exists and is not empty
    if [[ ! -s "$input_file" ]]; then
        echo "Error: httpx_live_subdomains.txt file is empty or does not exist. Please run httpx_recon.sh first to generate the list of live subdomains."
        return 1
    fi

    # Define the output files for crawling results
    output_file_hakrawler="$REPORT_DIR/hakrawler-urls.txt"
    output_file_katana="$REPORT_DIR/urls.txt"
    output_file_gospider="$REPORT_DIR/gospider-urls"
    output_file_gau="$REPORT_DIR/gau-urls.txt"

    # Run hakrawler to crawl the live subdomains and extract URLs
    echo "Starting crawling with hakrawler for live subdomains..."
    cat "$input_file" | hakrawler -subs >> "$output_file_hakrawler"
    echo "Hakrawler crawling completed. Results saved to $output_file_hakrawler"

    # Run katana to crawl the live subdomains and extract URLs
    echo "Starting crawling with katana for live subdomains..."
    katana -list "$input_file" -o "$output_file_katana"
    echo "Katana crawling completed. Results saved to $output_file_katana"

    # Run gospider to crawl the live subdomains and extract URLs
    echo "Starting crawling with gospider for live subdomains..."
    gospider -S "$input_file" -o "$output_file_gospider" -c 10 -d 1 -t 20
    echo "Gospider crawling completed. Results saved to $output_file_gospider"

    # Run gau to fetch known URLs from the live subdomains
    echo "Starting URL fetching with gau for live subdomains..."
    cat "$input_file" | gau --threads 4 --o "$output_file_gau"
    echo "Gau URL fetching completed. Results saved to $output_file_gau"
}