#!/bin/bash

# This script performs HTTPX reconnaissance for a given domain name using the httpx tool.
httpx_recon() {
    # Get the list of subdomains from the Subdomains.txt file generated by the subdomain_recon.sh script
    input_file="$REPORT_DIR/Subdomains.txt"

    # Check if the input file exists and is not empty
    if [[ ! -s "$input_file" ]]; then
        echo "Error: Subdomains.txt file is empty or does not exist. Please run subdomain_recon.sh first to generate the list of subdomains."
        return 1
    fi

    # Define the output files for httpx results
    output_file="$REPORT_DIR/httpx_results.txt"

    # Define the output file for live subdomains
    output_file_live_subdomains="$REPORT_DIR/httpx_live_subdomains.txt"

    # Run httpx to detects the technologies, status codes, titles, servers, and IP addresses of the subdomains.
    echo "Starting HTTPX reconnaissance for $domain_name..."
    httpx -l "$input_file" \
           -follow-redirects \
           -tech-detect \
           -status-code \
           -title \
           -server \
           -ip \
           -o "$output_file"
    echo "HTTPX reconnaissance completed. Results saved to $output_file"

    echo "Extracting live subdomains from the httpx results..."
    # Use awk to filter the httpx results for live subdomains based on status codes (200, 301, 302, 401, 403) and save them to a separate file
    awk '/\[(200|201|204|301|302|304|400|401|403|404|429|500|502|503)\]/{print $1}' "$output_file" | sed -E 's|https?://||; s|/.*||' > "$output_file_live_subdomains"
}