#!/bin/bash

# This script run the nmap scan to get IP addresses of all subdomains
Ip_Getter() {
    # Get the list of subdomains from the Subdomains.txt file generated by the subdomain_recon.sh script
    input_file="$REPORT_DIR/httpx_live_subdomains.txt"

    # Check if the input file exists and is not empty
    if [[ ! -s "$input_file" ]]; then
        echo "Error: httpx_live_subdomains.txt file is empty or does not exist. Please run httpx.sh first to generate the list of live subdomains."
        return 1
    fi

    # Define the output file for IP addresses
    output_file="$REPORT_DIR/alldomain-ip.txt"

    # Run nmap to get IP addresses of all subdomains and save the results to the output file
    echo "Starting nmap scan to get IP addresses of all subdomains..."
    nmap -sL -iL "$input_file" | grep "Nmap scan report" | sed -E 's/Nmap scan report for (.+) \((.+)\)/\1 --> \2/' > "$output_file"
    echo "Nmap scan completed. IP addresses saved to $output_file"
}
