#! /bin/bash

JS_Enum() {
    echo "Starting JavaScript Enumeration for $domain_name..."

    # Get the list of JavaScript files from the JS_Enum.txt file generated by the JS_Enum.sh script
    input_file="$REPORT_DIR/httpx_live_subdomains.txt"
    output_file="$REPORT_DIR/JS_Enum.txt"

    # Run subjs to enumerate JavaScript files and save the results to the output file
    katana -list "$input_file" -jc -kf all -ef woff,css,png,svg,jpg | grep -E '\.js$' | sort -u > "$output_file"

    echo "JavaScript enumeration completed. Results saved to $output_file"
}