#!/bin/bash

Port_Scanner() {
    # Get the list of subdomains from the Subdomains.txt file generated by the subdomain_recon.sh script
    input_file="$REPORT_DIR/httpx_live_subdomains.txt"

    # Check if the input file exists and is not empty
    if [[ ! -s "$input_file" ]]; then
        echo "Error: httpx_live_subdomains.txt file is empty or does not exist. Please run httpx.sh first to generate the list of live subdomains."
        return 1
    fi

    # Define the output file for port scan results
    output_file="$REPORT_DIR/port_scan_results.txt"

    # Run nmap to perform a port scan with version detection, os fingerprinting on all live subdomains and save the results to the output file
    echo "Starting nmap port scan on all live subdomains..."
    # Use sudo to ensure nmap has the necessary permissions to perform the scan 
    sudo nmap -iL "$input_file" -p- -sV -sC -O -T4 -oN "$output_file"
    echo "Nmap port scan completed. Results saved to $output_file"
}