#!/bin/bash

# This script performs subdomain enumeration for a given domain name using the subfinder tool.
subdomain_recon() {

    # Get the list of subdomains from the Subdomains.txt file generated by the subdomain_recon.sh script
    output_file="$REPORT_DIR/Subdomains.txt"
    echo "Starting subdomain enumeration for $domain_name..."

    # Run subfinder, assetfinder, and amass to enumerate subdomains and save the results to the output file
    subfinder -d "$domain_name" -all -o $output_file
    assetfinder --subs-only $domain_name | tee -a $output_file
    amass enum -active -d $domain_name
    amass subs -d $domain_name -names | tee -a $output_file
    echo "Subdomain enumeration completed. Results saved to $output_file"

    # Sort the output file to remove duplicates and save the sorted results back to the same file
    sort -u $output_file -o "$output_file"
}


